### PR TITLE
Update @ember/test-helpers dependency to v3

### PR DESCRIPTION
**Pull request by simonihmig**
This is technically a breaking change, so we would have to cut a new major release.

### CODE REVIEW

**Comment by simonihmig** [comment]
As we have to cut a new major anyway, does it make sense to reduce our Ember version support coverage with the same release? We go back to v3.24 here. Ideally, I would have said let's only support Ember versions that are supported themselves, but that would only be 5.x, and for reasons we cannot do that! 😅 

Maybe back to 4.8?

**Comment by ynotdraw** [comment]
> As we have to cut a new major anyway, does it make sense to reduce our Ember version support coverage with the same release? We go back to v3.24 here. Ideally, I would have said let's only support Ember versions that are supported themselves, but that would only be 5.x, and for reasons we cannot do that! 😅
> 
> Maybe back to 4.8?

Makes sense to me to only go back to 4.8.  I like that idea 👍

**Review by kellyselden — APPROVED** [review]

**Comment by simonihmig** [comment]
This repo needs two approvals before merging. @ynotdraw mind ticking the box? :) 

> Also good with a breaking change. [Looks like](https://github.com/CrowdStrike/ember-aria-utilities/blob/main/.github/workflows/ci.yml#L166C34-L166C50) we use semantic commits for the releases rather than changesets in this repo

Yeah, my commit message was `feat!: Update @ember/test-helpers dependency to v3`. The exclamation mark would mark that as a breaking change using conventional commits IIRC, right?

**Review by ynotdraw — APPROVED** [review]

**Comment by ynotdraw** [comment]
> Yeah, my commit message was feat!: Update @ember/test-helpers dependency to v3. The exclamation mark would mark that as a breaking change using conventional commits IIRC, right?

I'm not sure reading https://github.com/semantic-release/semantic-release.  Looking at https://stackoverflow.com/questions/70781241/semantic-release-breaking-change-using-exclamation-mark and https://github.com/CrowdStrike/ember-aria-utilities/blob/main/.github/workflows/ci.yml#L166 makes me think we may need to configure it, but I don't remember! 🙈 Guess we can find out!

**Comment by simonihmig** [comment]
Interesting! I'll rephrase the commit message with an explicit `BREAKING CHANGE` section then to make sure this works as expected!

**Comment by simonihmig** [comment]
Merging this to a temporary [batch-breaking-changes](https://github.com/CrowdStrike/ember-aria-utilities/tree/batch-breaking-changes) branch, to aggregate all breaking changes and not create a couple of new majors in short succession...

**Pull request merged**
